# Generated by Django 4.2.5 on 2023-09-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contect",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("passwd", models.CharField(max_length=200)),
                ("desc", models.TextField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="blog", name="content", field=models.TextField(max_length=10000),
        ),
    ]
